/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_db;

import javax.swing.SwingUtilities;

/**
 *
 * @author usuario
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Main() {
        //this.setExtendedState(this.MAXIMIZED_BOTH);
        initComponents();
         this.setLocationRelativeTo(null);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonEliminar = new javax.swing.JButton();
        botonRegistros = new javax.swing.JButton();
        botonConsultas = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        TablaPos = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonEliminar.setBackground(new java.awt.Color(0, 0, 0));
        botonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminar.setText("Eliminar registros");
        botonEliminar.setName("b_consultas"); // NOI18N
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 170, 30));

        botonRegistros.setBackground(new java.awt.Color(0, 0, 0));
        botonRegistros.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistros.setText("Registro");
        botonRegistros.setName("b_consultas"); // NOI18N
        botonRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrosActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 170, 30));

        botonConsultas.setBackground(new java.awt.Color(0, 0, 0));
        botonConsultas.setForeground(new java.awt.Color(255, 255, 255));
        botonConsultas.setText("Consultas");
        botonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(botonConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 170, 30));

        Salir.setBackground(new java.awt.Color(0, 0, 0));
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 60, -1));

        TablaPos.setBackground(new java.awt.Color(0, 0, 0));
        TablaPos.setForeground(new java.awt.Color(255, 255, 255));
        TablaPos.setText("Tabla de posiciones");
        TablaPos.setName("b_consultas"); // NOI18N
        TablaPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TablaPosActionPerformed(evt);
            }
        });
        getContentPane().add(TablaPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 170, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenIntro.jpg"))); // NOI18N
        Fondo.setText("jLabel2");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrosActionPerformed
        VistaConsulta vistaCon = new VistaConsulta();
        vistaCon.correr();
        this.setVisible(false);
    }//GEN-LAST:event_botonRegistrosActionPerformed

    private void botonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultasActionPerformed
                                                     
        VistaConsultaPartido vistaRegistroP = new VistaConsultaPartido();
        vistaRegistroP.run();
        this.setVisible(false);
    
    }//GEN-LAST:event_botonConsultasActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        VistaEliminar vistaE = new VistaEliminar();
        vistaE.correr();
        this.setVisible(false);
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void TablaPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TablaPosActionPerformed
        VistaTablaPosiciones vista = new VistaTablaPosiciones();
        vista.correr();
        this.setVisible(false);
    }//GEN-LAST:event_TablaPosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Salir;
    private javax.swing.JButton TablaPos;
    private javax.swing.JButton botonConsultas;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonRegistros;
    // End of variables declaration//GEN-END:variables
}
