/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_db;

import conection.Cancha;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class VistaRegistroCancha extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroCancha
     */
    public VistaRegistroCancha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        IdentificacionCancha = new javax.swing.JTextField();
        Identificacion1 = new javax.swing.JLabel();
        Capacidad = new javax.swing.JLabel();
        CapacidadCancha = new javax.swing.JTextField();
        Medidas = new javax.swing.JLabel();
        MedidadCancha = new javax.swing.JTextField();
        RegistrarCambios = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        CampoNombre = new javax.swing.JTextField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Nombre:");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Registro Cancha");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        IdentificacionCancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdentificacionCanchaActionPerformed(evt);
            }
        });
        getContentPane().add(IdentificacionCancha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 210, 30));

        Identificacion1.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Identificacion1.setForeground(new java.awt.Color(255, 255, 255));
        Identificacion1.setText("Identificación:");
        getContentPane().add(Identificacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, -1));

        Capacidad.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Capacidad.setForeground(new java.awt.Color(255, 255, 255));
        Capacidad.setText("Capacidad:");
        getContentPane().add(Capacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, -1, -1));

        CapacidadCancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadCanchaActionPerformed(evt);
            }
        });
        getContentPane().add(CapacidadCancha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 210, 30));

        Medidas.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Medidas.setForeground(new java.awt.Color(255, 255, 255));
        Medidas.setText("Medidas:");
        getContentPane().add(Medidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));
        getContentPane().add(MedidadCancha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 210, 30));

        RegistrarCambios.setBackground(new java.awt.Color(0, 0, 0));
        RegistrarCambios.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        RegistrarCambios.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarCambios.setText("Ingresar");
        RegistrarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 100, 40));

        Atras.setBackground(new java.awt.Color(0, 0, 0));
        Atras.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Atras.setForeground(new java.awt.Color(255, 255, 255));
        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 50, 110, 30));
        getContentPane().add(CampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 210, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1640, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CapacidadCanchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadCanchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapacidadCanchaActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.setVisible(false);
        VistaConsulta vistaCon = new VistaConsulta();
        vistaCon.setVisible(true);

    }//GEN-LAST:event_AtrasActionPerformed

    private void RegistrarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarCambiosActionPerformed
        
        Cancha ch = new Cancha();
        int id = parseInt(IdentificacionCancha.getText());
        int cap = parseInt(CapacidadCancha.getText());
        int med = parseInt(MedidadCancha.getText());
        String nom= CampoNombre.getText();
        ch.AgregarCancha(id, cap, med, nom);
        IdentificacionCancha.setText("");
        CapacidadCancha.setText("");
        MedidadCancha.setText("");
        CampoNombre.setText("");
        
    }//GEN-LAST:event_RegistrarCambiosActionPerformed

    private void IdentificacionCanchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdentificacionCanchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdentificacionCanchaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void correr() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroCancha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroCancha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroCancha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroCancha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroCancha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JLabel Capacidad;
    private javax.swing.JTextField CapacidadCancha;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Identificacion1;
    private javax.swing.JTextField IdentificacionCancha;
    private javax.swing.JTextField MedidadCancha;
    private javax.swing.JLabel Medidas;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton RegistrarCambios;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
