/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_db;

import conection.Equipo;
import static java.lang.Integer.parseInt;

/**
 *
 * @author usuario
 */
public class VistaRegistroEquipo extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroEquipo
     */
    public VistaRegistroEquipo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        NombreEquipo = new javax.swing.JTextField();
        IdEquipo = new javax.swing.JLabel();
        IdentificacionEquipo = new javax.swing.JTextField();
        Eslogan = new javax.swing.JLabel();
        bIngresar = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        EsloganEquipo = new javax.swing.JTextField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Registro Equipo");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 370, 50));

        Nombre.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Nombre:");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 70, 20));

        NombreEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(NombreEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 210, 30));

        IdEquipo.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        IdEquipo.setForeground(new java.awt.Color(255, 255, 255));
        IdEquipo.setText("Identificación:");
        getContentPane().add(IdEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 130, 20));
        getContentPane().add(IdentificacionEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 210, 30));

        Eslogan.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Eslogan.setForeground(new java.awt.Color(255, 255, 255));
        Eslogan.setText("Eslogan:");
        getContentPane().add(Eslogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 70, -1));

        bIngresar.setBackground(new java.awt.Color(0, 0, 0));
        bIngresar.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        bIngresar.setForeground(new java.awt.Color(255, 255, 255));
        bIngresar.setText("Ingresar");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(bIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 230, 40));

        Atras.setBackground(new java.awt.Color(0, 0, 0));
        Atras.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Atras.setForeground(new java.awt.Color(255, 255, 255));
        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 50, 110, 30));

        EsloganEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsloganEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(EsloganEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 210, 30));

        Fondo.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Fondo.setForeground(new java.awt.Color(255, 255, 255));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1720, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEquipoActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.setVisible(false);
        VistaConsulta vistaCon = new VistaConsulta();
        vistaCon.setVisible(true);
        
              
    }//GEN-LAST:event_AtrasActionPerformed

    private void EsloganEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsloganEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EsloganEquipoActionPerformed

    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed
        Equipo eq = new Equipo();
        int id= parseInt(IdentificacionEquipo.getText());
        String nom = NombreEquipo.getText();
        String es = EsloganEquipo.getText();
        eq.AgregarEquipo(id, nom, es);
        IdentificacionEquipo.setText("");
        NombreEquipo.setText("");
        EsloganEquipo.setText("");
        
    }//GEN-LAST:event_bIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void correr(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JLabel Eslogan;
    private javax.swing.JTextField EsloganEquipo;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel IdEquipo;
    private javax.swing.JTextField IdentificacionEquipo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreEquipo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton bIngresar;
    // End of variables declaration//GEN-END:variables
}
