/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_db;

import conection.Jugador;
import static java.lang.Integer.parseInt;

/**
 *
 * @author hassler-pc
 */
public class VistaRegistroJugador extends javax.swing.JFrame {

    /**
     * Creates new form FrameJugador
     */
    public VistaRegistroJugador() {
        initComponents();
        this.setLocationRelativeTo(null);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        NombreJugador = new javax.swing.JLabel();
        IdJugador = new javax.swing.JLabel();
        PrimerApellido = new javax.swing.JLabel();
        SegundoApellido = new javax.swing.JLabel();
        NumeroDeCAmiseta = new javax.swing.JLabel();
        SegundoApellido1 = new javax.swing.JLabel();
        ContenidoPrimerApellido = new javax.swing.JTextField();
        NombreDelJugador1 = new javax.swing.JTextField();
        ContenidoSegundoApellido = new javax.swing.JTextField();
        ContenidoIdentificacion = new javax.swing.JTextField();
        ContenidoNumeroDeCamisa = new javax.swing.JTextField();
        ContenidoIdEquipo = new javax.swing.JTextField();
        IngresarJugador = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        Titulo.setForeground(java.awt.Color.white);
        Titulo.setText("Registro Jugador");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        NombreJugador.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        NombreJugador.setForeground(java.awt.Color.white);
        NombreJugador.setText("Nombre Jugador:");
        getContentPane().add(NombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        IdJugador.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        IdJugador.setForeground(java.awt.Color.white);
        IdJugador.setText("Identificación");
        getContentPane().add(IdJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, -1, -1));

        PrimerApellido.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        PrimerApellido.setForeground(java.awt.Color.white);
        PrimerApellido.setText("Primer Apellido");
        getContentPane().add(PrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, -1));

        SegundoApellido.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        SegundoApellido.setForeground(java.awt.Color.white);
        SegundoApellido.setText("Segundo Apellido");
        getContentPane().add(SegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        NumeroDeCAmiseta.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        NumeroDeCAmiseta.setForeground(java.awt.Color.white);
        NumeroDeCAmiseta.setText("Numero de Camiseta");
        getContentPane().add(NumeroDeCAmiseta, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, -1, -1));

        SegundoApellido1.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        SegundoApellido1.setForeground(java.awt.Color.white);
        SegundoApellido1.setText("Identificación del equipo:");
        getContentPane().add(SegundoApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 570, -1, 20));

        ContenidoPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContenidoPrimerApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(ContenidoPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 210, 30));

        NombreDelJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreDelJugador1ActionPerformed(evt);
            }
        });
        getContentPane().add(NombreDelJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 210, 30));

        ContenidoSegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContenidoSegundoApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(ContenidoSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 210, 30));

        ContenidoIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContenidoIdentificacionActionPerformed(evt);
            }
        });
        getContentPane().add(ContenidoIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 210, 30));

        ContenidoNumeroDeCamisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContenidoNumeroDeCamisaActionPerformed(evt);
            }
        });
        getContentPane().add(ContenidoNumeroDeCamisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 210, 30));

        ContenidoIdEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContenidoIdEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(ContenidoIdEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 610, 210, 30));

        IngresarJugador.setBackground(new java.awt.Color(0, 0, 0));
        IngresarJugador.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        IngresarJugador.setForeground(new java.awt.Color(255, 255, 255));
        IngresarJugador.setText("Ingresar");
        IngresarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(IngresarJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 670, 140, 40));

        Atras.setBackground(new java.awt.Color(0, 0, 0));
        Atras.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Atras.setForeground(new java.awt.Color(255, 255, 255));
        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 30, 120, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        Fondo.setText("Fondo");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1591, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContenidoPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContenidoPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContenidoPrimerApellidoActionPerformed

    private void NombreDelJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreDelJugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreDelJugador1ActionPerformed

    private void ContenidoSegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContenidoSegundoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContenidoSegundoApellidoActionPerformed

    private void ContenidoIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContenidoIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContenidoIdentificacionActionPerformed

    private void ContenidoNumeroDeCamisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContenidoNumeroDeCamisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContenidoNumeroDeCamisaActionPerformed

    private void ContenidoIdEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContenidoIdEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContenidoIdEquipoActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.setVisible(false);
        VistaConsulta vistaCon = new VistaConsulta();
        vistaCon.setVisible(true);

    }//GEN-LAST:event_AtrasActionPerformed

    private void IngresarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarJugadorActionPerformed
        Jugador ju = new Jugador();
        String nom=NombreDelJugador1.getText();
        String ap1=ContenidoPrimerApellido.getText();
        String ap2 = ContenidoSegundoApellido.getText();
        int id = parseInt(ContenidoIdentificacion.getText());
        int num = parseInt(ContenidoNumeroDeCamisa.getText());
        int ide = parseInt(ContenidoIdEquipo.getText());
        int goles=0;
        int estado=1;
        ju.AgregarJugador(id, nom, ap1, ap2, num, goles, estado, ide);
        NombreDelJugador1.setText("");
        ContenidoPrimerApellido.setText("");
        ContenidoSegundoApellido.setText("");
        ContenidoIdentificacion.setText("");
        ContenidoNumeroDeCamisa.setText("");
        ContenidoIdEquipo.setText("");
    }//GEN-LAST:event_IngresarJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void correr()  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JTextField ContenidoIdEquipo;
    private javax.swing.JTextField ContenidoIdentificacion;
    private javax.swing.JTextField ContenidoNumeroDeCamisa;
    private javax.swing.JTextField ContenidoPrimerApellido;
    private javax.swing.JTextField ContenidoSegundoApellido;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel IdJugador;
    private javax.swing.JButton IngresarJugador;
    private javax.swing.JTextField NombreDelJugador1;
    private javax.swing.JLabel NombreJugador;
    private javax.swing.JLabel NumeroDeCAmiseta;
    private javax.swing.JLabel PrimerApellido;
    private javax.swing.JLabel SegundoApellido;
    private javax.swing.JLabel SegundoApellido1;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
