/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_db;
import com.sun.javafx.image.impl.IntArgb;
import conection.VariadosPartido;
/**
 *
 * @author usuario
 */
public class VistaRegistroPartido extends javax.swing.JFrame {
    public static int partido = 0;
    /**
     * Creates new form VistaRegistroPartido
     */
    public VistaRegistroPartido() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Tiempo = new javax.swing.JLabel();
        Equipo_L = new javax.swing.JLabel();
        Equipo_V = new javax.swing.JLabel();
        Cancha = new javax.swing.JLabel();
        Identificación = new javax.swing.JLabel();
        Marcador = new javax.swing.JLabel();
        Arbitro_C = new javax.swing.JLabel();
        Arbitro_L = new javax.swing.JLabel();
        Arbitro_L2 = new javax.swing.JLabel();
        Arbitro_Cuarto = new javax.swing.JLabel();
        EquipoLocal = new javax.swing.JTextField();
        EquipoVisitante = new javax.swing.JTextField();
        IdentificacionPartido = new javax.swing.JTextField();
        TiempoPartido = new javax.swing.JTextField();
        MarcadorPartido = new javax.swing.JTextField();
        CanchaPartido = new javax.swing.JTextField();
        ArbitroCentralPartido = new javax.swing.JTextField();
        ArbitroLateral1lPartido = new javax.swing.JTextField();
        ArbitroLateral2Partido = new javax.swing.JTextField();
        ArbitroCuartoPartido = new javax.swing.JTextField();
        Atras = new javax.swing.JButton();
        Ingresar = new javax.swing.JButton();
        IngresarGoles = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        Titulo.setForeground(java.awt.Color.white);
        Titulo.setText("Registro Partido");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        Tiempo.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Tiempo.setForeground(new java.awt.Color(255, 255, 255));
        Tiempo.setText("Tiempo:");
        getContentPane().add(Tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        Equipo_L.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Equipo_L.setForeground(new java.awt.Color(255, 255, 255));
        Equipo_L.setText("Equipo Local:");
        getContentPane().add(Equipo_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        Equipo_V.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Equipo_V.setForeground(new java.awt.Color(255, 255, 255));
        Equipo_V.setText("Equipo Visitante:");
        getContentPane().add(Equipo_V, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, 20));

        Cancha.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Cancha.setForeground(new java.awt.Color(255, 255, 255));
        Cancha.setText("Cancha:");
        getContentPane().add(Cancha, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, -1, -1));

        Identificación.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Identificación.setForeground(new java.awt.Color(255, 255, 255));
        Identificación.setText("Identificación:");
        getContentPane().add(Identificación, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        Marcador.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Marcador.setForeground(new java.awt.Color(255, 255, 255));
        Marcador.setText("Marcador:");
        getContentPane().add(Marcador, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, -1, -1));

        Arbitro_C.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Arbitro_C.setForeground(new java.awt.Color(255, 255, 255));
        Arbitro_C.setText("Arbitro Central:");
        getContentPane().add(Arbitro_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, -1, -1));

        Arbitro_L.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Arbitro_L.setForeground(new java.awt.Color(255, 255, 255));
        Arbitro_L.setText("Arbitro Lateral 1:");
        getContentPane().add(Arbitro_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, -1, -1));

        Arbitro_L2.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Arbitro_L2.setForeground(new java.awt.Color(255, 255, 255));
        Arbitro_L2.setText("Arbitro Lateral 2:");
        getContentPane().add(Arbitro_L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, -1, -1));

        Arbitro_Cuarto.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Arbitro_Cuarto.setForeground(new java.awt.Color(255, 255, 255));
        Arbitro_Cuarto.setText("Cuarto Arbitro:");
        getContentPane().add(Arbitro_Cuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, -1, -1));

        EquipoLocal.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        EquipoLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoLocalActionPerformed(evt);
            }
        });
        getContentPane().add(EquipoLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 210, 30));

        EquipoVisitante.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        EquipoVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoVisitanteActionPerformed(evt);
            }
        });
        getContentPane().add(EquipoVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 210, 30));

        IdentificacionPartido.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        IdentificacionPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdentificacionPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(IdentificacionPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 210, 30));

        TiempoPartido.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        TiempoPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiempoPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(TiempoPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 210, 30));

        MarcadorPartido.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        MarcadorPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcadorPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(MarcadorPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 210, 30));

        CanchaPartido.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        CanchaPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanchaPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(CanchaPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 210, 30));

        ArbitroCentralPartido.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        ArbitroCentralPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArbitroCentralPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(ArbitroCentralPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 210, 30));

        ArbitroLateral1lPartido.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        ArbitroLateral1lPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArbitroLateral1lPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(ArbitroLateral1lPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 210, 30));

        ArbitroLateral2Partido.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        ArbitroLateral2Partido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArbitroLateral2PartidoActionPerformed(evt);
            }
        });
        getContentPane().add(ArbitroLateral2Partido, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 210, 30));

        ArbitroCuartoPartido.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        ArbitroCuartoPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArbitroCuartoPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(ArbitroCuartoPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 210, 30));

        Atras.setBackground(new java.awt.Color(0, 0, 0));
        Atras.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Atras.setForeground(new java.awt.Color(255, 255, 255));
        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 50, 120, 40));

        Ingresar.setBackground(new java.awt.Color(0, 0, 0));
        Ingresar.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        getContentPane().add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, 210, 30));

        IngresarGoles.setText("Ingresar Goles");
        IngresarGoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarGolesActionPerformed(evt);
            }
        });
        getContentPane().add(IngresarGoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, 210, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -50, 1390, 990));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EquipoLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoLocalActionPerformed

    private void EquipoVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoVisitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoVisitanteActionPerformed

    private void IdentificacionPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdentificacionPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdentificacionPartidoActionPerformed

    private void TiempoPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiempoPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TiempoPartidoActionPerformed

    private void MarcadorPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcadorPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcadorPartidoActionPerformed

    private void CanchaPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanchaPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CanchaPartidoActionPerformed

    private void ArbitroCentralPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArbitroCentralPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArbitroCentralPartidoActionPerformed

    private void ArbitroLateral1lPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArbitroLateral1lPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArbitroLateral1lPartidoActionPerformed

    private void ArbitroLateral2PartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArbitroLateral2PartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArbitroLateral2PartidoActionPerformed

    private void ArbitroCuartoPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArbitroCuartoPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArbitroCuartoPartidoActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.setVisible(false);
        VistaConsulta vistaCon = new VistaConsulta();
        vistaCon.setVisible(true);
    }//GEN-LAST:event_AtrasActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        VariadosPartido vp = new VariadosPartido();
        vp.agregarPartido(EquipoLocal.getText(), EquipoVisitante.getText(), CanchaPartido.getText(), 
                Integer.parseInt(IdentificacionPartido.getText()), Integer.parseInt(TiempoPartido.getText()));
        vp.agregarPartidoArbitro(Integer.parseInt(IdentificacionPartido.getText()), 
                Integer.parseInt(ArbitroCentralPartido.getText()), 
                Integer.parseInt(ArbitroLateral1lPartido.getText()), 
                Integer.parseInt(ArbitroLateral2Partido.getText()), 
                Integer.parseInt(ArbitroCuartoPartido.getText()));
        
        vp.agregarInforme(Integer.parseInt(IdentificacionPartido.getText()),MarcadorPartido.getText());
        
        vp.SumarPuntos(EquipoLocal.getText(), EquipoVisitante.getText(), MarcadorPartido.getText());
        IdentificacionPartido.setText("");
        ArbitroCuartoPartido.setText("");
        ArbitroLateral2Partido.setText("");
        ArbitroLateral1lPartido.setText("");
        ArbitroCentralPartido.setText("");
        TiempoPartido.setText("");
        CanchaPartido.setText("");
        EquipoVisitante.setText("");
        EquipoLocal.setText("");
        MarcadorPartido.setText("");
    }//GEN-LAST:event_IngresarActionPerformed

    private void IngresarGolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarGolesActionPerformed
        VistaIngresarGoles vig = new VistaIngresarGoles();
        vig.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_IngresarGolesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void correr()  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroPartido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArbitroCentralPartido;
    private javax.swing.JTextField ArbitroCuartoPartido;
    private javax.swing.JTextField ArbitroLateral1lPartido;
    private javax.swing.JTextField ArbitroLateral2Partido;
    private javax.swing.JLabel Arbitro_C;
    private javax.swing.JLabel Arbitro_Cuarto;
    private javax.swing.JLabel Arbitro_L;
    private javax.swing.JLabel Arbitro_L2;
    private javax.swing.JButton Atras;
    private javax.swing.JLabel Cancha;
    private javax.swing.JTextField CanchaPartido;
    private javax.swing.JTextField EquipoLocal;
    private javax.swing.JTextField EquipoVisitante;
    private javax.swing.JLabel Equipo_L;
    private javax.swing.JLabel Equipo_V;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField IdentificacionPartido;
    private javax.swing.JLabel Identificación;
    private javax.swing.JButton Ingresar;
    private javax.swing.JButton IngresarGoles;
    private javax.swing.JLabel Marcador;
    private javax.swing.JTextField MarcadorPartido;
    private javax.swing.JLabel Tiempo;
    private javax.swing.JTextField TiempoPartido;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
