/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_db;

import conection.MySQL;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class VistaConsultaPremiacion extends javax.swing.JFrame {

    /**
     * Creates new form VistaConsultaPremiacion
     */
    public VistaConsultaPremiacion() {
        initComponents();
        
         DefaultTableModel mod1= new DefaultTableModel();
        mod1.addColumn("Equipo Campeón");
        TablaCampeon.setModel(mod1);
        
        DefaultTableModel mod2 = new DefaultTableModel();
        mod2.addColumn("Equipo Subcampeón");
        TablaSubCampeon.setModel(mod2);
        
        DefaultTableModel mod3 = new DefaultTableModel();
        mod3.addColumn("Marcador");
        TablaMarcador.setModel(mod3);
        
        DefaultTableModel mod4 = new DefaultTableModel();
        mod4.addColumn("Nombre");
        mod4.addColumn("Primer Apellido");
        mod4.addColumn("Segundo Apellido");
        mod4.addColumn("Goles Anotados");
        TablaJugador.setModel(mod4);
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        EquipoCampeón = new javax.swing.JCheckBox();
        Marcador = new javax.swing.JCheckBox();
        EquipoSubCampeón = new javax.swing.JCheckBox();
        JugadorGoleador = new javax.swing.JCheckBox();
        Consultar = new javax.swing.JButton();
        AnteriorConsulta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaCampeon = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSubCampeon = new javax.swing.JTable();
        Atras = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaJugador = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaMarcador = new javax.swing.JTable();
        Limpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Consultas de Premiación Torneo");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 680, -1));

        EquipoCampeón.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EquipoCampeón.setForeground(new java.awt.Color(255, 255, 255));
        EquipoCampeón.setText("Equipo Campeón");
        getContentPane().add(EquipoCampeón, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 230, 30));

        Marcador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Marcador.setForeground(new java.awt.Color(255, 255, 255));
        Marcador.setText("Marcador");
        Marcador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcadorActionPerformed(evt);
            }
        });
        getContentPane().add(Marcador, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 230, 30));

        EquipoSubCampeón.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EquipoSubCampeón.setForeground(new java.awt.Color(255, 255, 255));
        EquipoSubCampeón.setText("Equipo Sub-Campeón");
        getContentPane().add(EquipoSubCampeón, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 230, 30));

        JugadorGoleador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JugadorGoleador.setForeground(new java.awt.Color(255, 255, 255));
        JugadorGoleador.setText("Jugador Goleador");
        JugadorGoleador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugadorGoleadorActionPerformed(evt);
            }
        });
        getContentPane().add(JugadorGoleador, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 230, 30));

        Consultar.setBackground(new java.awt.Color(0, 0, 0));
        Consultar.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Consultar.setForeground(new java.awt.Color(255, 255, 255));
        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 150, 60));

        AnteriorConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/anterior.jpg"))); // NOI18N
        AnteriorConsulta.setText(">>");
        AnteriorConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(AnteriorConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 70, 80));

        TablaCampeon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TablaCampeon);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 490, 50));

        TablaSubCampeon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaSubCampeon);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 490, 50));

        Atras.setBackground(new java.awt.Color(0, 0, 0));
        Atras.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Atras.setForeground(new java.awt.Color(255, 255, 255));
        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 40, 110, 30));

        TablaJugador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TablaJugador);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 490, 50));

        TablaMarcador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(TablaMarcador);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 490, 50));

        Limpiar.setBackground(new java.awt.Color(0, 0, 0));
        Limpiar.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1610, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MarcadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcadorActionPerformed

    private void AnteriorConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorConsultaActionPerformed
        VistaConsultaSancionados vistaConsultaS = new VistaConsultaSancionados();
        vistaConsultaS.run();
        this.setVisible(false);
    }//GEN-LAST:event_AnteriorConsultaActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
  
         
        if(EquipoCampeón.isSelected()){
            LlenarEquipoCampeon();
        }
         
         if(EquipoSubCampeón.isSelected()){
             LlenarEquipoSubCampeon();
         }
         
         if(JugadorGoleador.isSelected()){
            LlenarJugadorGoleador();
         }
         
         if(Marcador.isSelected()){
             LlenarMarcador();
         }
        
    }//GEN-LAST:event_ConsultarActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.setVisible(false);
        Main main = new Main();
        main.setVisible(true);
    }//GEN-LAST:event_AtrasActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
         DefaultTableModel mod1= new DefaultTableModel();
        mod1.addColumn("Equipo Campeón");
        TablaCampeon.setModel(mod1);
        
        DefaultTableModel mod2 = new DefaultTableModel();
        mod2.addColumn("Equipo Campeón");
        TablaSubCampeon.setModel(mod2);
        
        DefaultTableModel mod3 = new DefaultTableModel();
        mod3.addColumn("Marcador");
        TablaMarcador.setModel(mod3);
        
        DefaultTableModel mod4 = new DefaultTableModel();
        mod4.addColumn("Nombre");
        mod4.addColumn("Primer Apellido");
        mod4.addColumn("Segundo Apellido");
        mod4.addColumn("Goles Anotados");
        TablaJugador.setModel(mod4);
        
        EquipoCampeón.setSelected(false);
        EquipoSubCampeón.setSelected(false);
        JugadorGoleador.setSelected(false);
        Marcador.setSelected(false);
        
    }//GEN-LAST:event_LimpiarActionPerformed

    private void JugadorGoleadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugadorGoleadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JugadorGoleadorActionPerformed

    public void LlenarEquipoCampeon(){
        MySQL db = new MySQL();
        db.MySQLConnect();
        
        DefaultTableModel mod = new DefaultTableModel();
        mod.addColumn("Equipo Campeón");
        TablaCampeon.setModel(mod);
        try{
            db.comando = db.conexion.createStatement();
            db.registro = db.comando.executeQuery("select nombre from Partido_Final,Equipo where Equipo.idEquipo = Partido_Final.idEquipo_Campeon;");
            String [] datos = new String [1];
            while(db.registro.next()){
                datos[0]=db.registro.getString(1);          
                mod.addRow(datos);
                break;
            }
            TablaCampeon.setModel(mod);
            db.close();
        }catch(Exception e){
            System.out.println(e);
        }
        db.close();
    }
        public void LlenarEquipoSubCampeon(){
        MySQL db = new MySQL();
        db.MySQLConnect();
        
        DefaultTableModel mod = new DefaultTableModel();
        mod.addColumn("Equipo Campeón");
        TablaSubCampeon.setModel(mod);
        try{
        db.comando = db.conexion.createStatement();
        db.registro = db.comando.executeQuery("select nombre from Partido_Final,Equipo where Equipo.idEquipo = Partido_Final.idEquipo_Subcampeon;");
        String [] datos = new String [1];
        while(db.registro.next()){
            datos[0]=db.registro.getString(1);
            mod.addRow(datos);
            break;
        }
        TablaSubCampeon.setModel(mod);
        db.close();
        }catch(Exception e){
            System.out.println(e);
        }
        db.close();
    }
    public void LlenarMarcador(){
        MySQL db = new MySQL();
        db.MySQLConnect();
        
        DefaultTableModel mod = new DefaultTableModel();
        mod.addColumn("Marcador");
        TablaMarcador.setModel(mod);
        try{
        db.comando = db.conexion.createStatement();
        db.registro = db.comando.executeQuery("select marcador from Partido_Final;");
        String [] datos = new String [1];
        while(db.registro.next()){
            datos[0]=db.registro.getString(1);
            mod.addRow(datos);
            break;
        }
        TablaMarcador.setModel(mod);
        db.close();
        }catch(Exception e){
            System.out.println(e);
        }
        db.close();
    }
     public void LlenarJugadorGoleador(){
        MySQL db = new MySQL();
        db.MySQLConnect();
        
        DefaultTableModel mod = new DefaultTableModel();
        mod.addColumn("Nombre");
        mod.addColumn("Apellido 1");
        mod.addColumn("Apellido 2");
        mod.addColumn("Goles Anotados");
        TablaJugador.setModel(mod);
        try{
        db.comando = db.conexion.createStatement();
        db.registro = db.comando.executeQuery("select nombre,apellido1,apellido2,num_goles from Jugador group by (idJugador) order by(num_goles) desc limit 1 ;");
        String [] datos = new String [4];
        while(db.registro.next()){
        datos[0]=db.registro.getString(1);
        datos[1]=db.registro.getString(2);
        datos[2]=db.registro.getString(3);    
        datos[3]=db.registro.getString(4);
        mod.addRow(datos);
    
        }
        TablaJugador.setModel(mod);
        db.close();
        }catch(Exception e){
            System.out.println(e);
        }
        db.close();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaPremiacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaPremiacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaPremiacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConsultaPremiacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConsultaPremiacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnteriorConsulta;
    private javax.swing.JButton Atras;
    private javax.swing.JButton Consultar;
    private javax.swing.JCheckBox EquipoCampeón;
    private javax.swing.JCheckBox EquipoSubCampeón;
    private javax.swing.JCheckBox JugadorGoleador;
    private javax.swing.JButton Limpiar;
    private javax.swing.JCheckBox Marcador;
    private javax.swing.JTable TablaCampeon;
    private javax.swing.JTable TablaJugador;
    private javax.swing.JTable TablaMarcador;
    private javax.swing.JTable TablaSubCampeon;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
