/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_db;

import conection.Eliminar;
import javax.swing.JTextField;

/**
 *
 * @author usuario
 */
public class VistaEliminar extends javax.swing.JFrame {

    /**
     * Creates new form VistaEliminar
     */
    public VistaEliminar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoDeEliminacion = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Identificacion = new javax.swing.JLabel();
        IdentificacionEliminar = new javax.swing.JTextField();
        Eliminar = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TipoDeEliminacion.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        TipoDeEliminacion.setForeground(new java.awt.Color(255, 255, 255));
        TipoDeEliminacion.setText("Seleccione el dato que desea eliminar:");
        getContentPane().add(TipoDeEliminacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 520, 40));

        Titulo.setFont(new java.awt.Font("Maiandra GD", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Eliminar Datos");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 460, 40));

        jComboBox1.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Partido", "Jugador", "Arbitro", "Cancha", "Partido Final", "Equipo" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 240, 30));

        Identificacion.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        Identificacion.setForeground(new java.awt.Color(255, 255, 255));
        Identificacion.setText("Ingrese la identificación:");
        getContentPane().add(Identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 460, 40));

        IdentificacionEliminar.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        getContentPane().add(IdentificacionEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 250, 30));

        Eliminar.setBackground(new java.awt.Color(0, 0, 0));
        Eliminar.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 170, 80));

        Atras.setBackground(new java.awt.Color(0, 0, 0));
        Atras.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Atras.setForeground(new java.awt.Color(255, 255, 255));
        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 40, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -160, 1730, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
          Eliminar eli = new Eliminar();
          
          String  identificacion =  IdentificacionEliminar.getText();
          String i =  jComboBox1.getSelectedItem().toString();
          
          if(i.equals("Partido")){
              eli.EliminarPartido(Integer.parseInt(identificacion));
          }
          if(i.equals("Jugador")){
              eli.EliminarJugador(Integer.parseInt(identificacion));
          }
          if(i.equals("Equipo")){
              eli.EliminarEquipo(Integer.parseInt(identificacion));
          }
          if(i.equals("Arbitro")){
              eli.EliminarArbitro(Integer.parseInt(identificacion));
          }
          if(i.equals("Cancha")){
              eli.EliminarCancha(Integer.parseInt(identificacion));
          }
          if(i.equals("Partido Final")){
              eli.EliminarPartidoFinal(Integer.parseInt(identificacion));
          }
          IdentificacionEliminar.setText("");
    }//GEN-LAST:event_EliminarActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.setVisible(false);
        Main main = new Main();
        main.setVisible(true);
    }//GEN-LAST:event_AtrasActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void correr() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel Identificacion;
    private javax.swing.JTextField IdentificacionEliminar;
    private javax.swing.JLabel TipoDeEliminacion;
    private javax.swing.JLabel Titulo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
