/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_db;
import conection.Equipo;
import conection.Partido;

/**
 *
 * @author usuario
 */
public class VistaPartidoFinal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPartidoFinal
     */
    public VistaPartidoFinal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EquipoLocal = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        Equipo_L = new javax.swing.JLabel();
        AgregarPartidoFinal = new javax.swing.JButton();
        Equipo_V = new javax.swing.JLabel();
        EquipoVisitante = new javax.swing.JTextField();
        Marcador = new javax.swing.JLabel();
        Goles = new javax.swing.JLabel();
        MarcadorPartidoFinal = new javax.swing.JTextField();
        BotonIngresar = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EquipoLocal.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        EquipoLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoLocalActionPerformed(evt);
            }
        });
        getContentPane().add(EquipoLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 210, 30));

        Titulo.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Partido Final");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 320, 40));

        Equipo_L.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Equipo_L.setForeground(new java.awt.Color(255, 255, 255));
        Equipo_L.setText("Equipo Local:");
        getContentPane().add(Equipo_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, -1, -1));

        AgregarPartidoFinal.setBackground(java.awt.Color.black);
        AgregarPartidoFinal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AgregarPartidoFinal.setForeground(java.awt.Color.white);
        AgregarPartidoFinal.setText("Ingresar");
        AgregarPartidoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPartidoFinalActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarPartidoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 620, 210, 30));

        Equipo_V.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Equipo_V.setForeground(new java.awt.Color(255, 255, 255));
        Equipo_V.setText("Equipo Visitante:");
        getContentPane().add(Equipo_V, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, 20));

        EquipoVisitante.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        EquipoVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoVisitanteActionPerformed(evt);
            }
        });
        getContentPane().add(EquipoVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 210, 30));

        Marcador.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Marcador.setForeground(new java.awt.Color(255, 255, 255));
        Marcador.setText("Marcador:");
        getContentPane().add(Marcador, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, -1, 20));

        Goles.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Goles.setForeground(new java.awt.Color(255, 255, 255));
        Goles.setText("Goles:");
        getContentPane().add(Goles, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, -1, 20));

        MarcadorPartidoFinal.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        MarcadorPartidoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcadorPartidoFinalActionPerformed(evt);
            }
        });
        getContentPane().add(MarcadorPartidoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 210, 30));

        BotonIngresar.setBackground(java.awt.Color.black);
        BotonIngresar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BotonIngresar.setForeground(java.awt.Color.white);
        BotonIngresar.setText("Ingresar Goles");
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 210, 30));

        Atras.setBackground(new java.awt.Color(0, 0, 0));
        Atras.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Atras.setForeground(new java.awt.Color(255, 255, 255));
        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 30, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 1610, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EquipoVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoVisitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoVisitanteActionPerformed

    private void MarcadorPartidoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcadorPartidoFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcadorPartidoFinalActionPerformed

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
        VistaIngresarGoles vig = new VistaIngresarGoles();
        vig.setVisible(true);

    }//GEN-LAST:event_BotonIngresarActionPerformed

    
    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.setVisible(false);
        VistaConsulta vistaCon = new VistaConsulta();
        vistaCon.setVisible(true);
    }//GEN-LAST:event_AtrasActionPerformed

    private void AgregarPartidoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPartidoFinalActionPerformed
        Partido partido = new Partido();
        String EquipoL = EquipoLocal.getText();
        String EquipoV = EquipoVisitante.getText();
        String resultado = MarcadorPartidoFinal.getText();
        partido.IngresarPartidoFinal(EquipoL, EquipoV, resultado);
        EquipoLocal.setText("");
        EquipoVisitante.setText("");
        MarcadorPartidoFinal.setText("");
    }//GEN-LAST:event_AgregarPartidoFinalActionPerformed

    private void EquipoLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoLocalActionPerformed

    }//GEN-LAST:event_EquipoLocalActionPerformed

    private void agregandoEquiposFinalistas(){
        Equipo eq = new Equipo();        
        String arr[] = eq.Equipos_Finalistas();  
        EquipoLocal.setText(arr[0]);
        EquipoVisitante.setText(arr[1]);
    }
    /**
     * @param args the command line arguments
     */
    public static void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPartidoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPartidoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPartidoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPartidoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            VistaPartidoFinal vp = new VistaPartidoFinal();
            vp.agregandoEquiposFinalistas();
            vp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarPartidoFinal;
    private javax.swing.JButton Atras;
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JTextField EquipoLocal;
    private javax.swing.JTextField EquipoVisitante;
    private javax.swing.JLabel Equipo_L;
    private javax.swing.JLabel Equipo_V;
    private javax.swing.JLabel Goles;
    private javax.swing.JLabel Marcador;
    private javax.swing.JTextField MarcadorPartidoFinal;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
