/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_db;

import conection.Arbitro;

/**
 *
 * @author hassler-pc
 */
public class VistaRegistroArbitro extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroArbitro
     */
    public VistaRegistroArbitro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistroArbitro = new javax.swing.JLabel();
        NombreArbitro = new javax.swing.JLabel();
        NombreArbitro1 = new javax.swing.JLabel();
        NombreArbitro2 = new javax.swing.JLabel();
        NombreArbitro4 = new javax.swing.JLabel();
        NombreArbitro3 = new javax.swing.JLabel();
        ContenidoNombreArbitro = new javax.swing.JTextField();
        ConPrimerApellidoArbitro = new javax.swing.JTextField();
        ContSegundoAPellidoArbitro = new javax.swing.JTextField();
        ContenidoTipoArbitro = new javax.swing.JTextField();
        ContenidoIdentificacionArbitro = new javax.swing.JTextField();
        BotonIngresar = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegistroArbitro.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        RegistroArbitro.setForeground(java.awt.Color.white);
        RegistroArbitro.setText("Registro Arbitro");
        getContentPane().add(RegistroArbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, 60));

        NombreArbitro.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        NombreArbitro.setForeground(java.awt.Color.white);
        NombreArbitro.setText("Identificación");
        getContentPane().add(NombreArbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, -1, -1));

        NombreArbitro1.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        NombreArbitro1.setForeground(java.awt.Color.white);
        NombreArbitro1.setText("Nombre:");
        getContentPane().add(NombreArbitro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, -1, -1));

        NombreArbitro2.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        NombreArbitro2.setForeground(java.awt.Color.white);
        NombreArbitro2.setText("Primer Apellido");
        getContentPane().add(NombreArbitro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        NombreArbitro4.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        NombreArbitro4.setForeground(java.awt.Color.white);
        NombreArbitro4.setText("Tipo de Arbitro");
        getContentPane().add(NombreArbitro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, -1, -1));

        NombreArbitro3.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        NombreArbitro3.setForeground(java.awt.Color.white);
        NombreArbitro3.setText("Segundo Apellido");
        getContentPane().add(NombreArbitro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, -1, -1));

        ContenidoNombreArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContenidoNombreArbitroActionPerformed(evt);
            }
        });
        getContentPane().add(ContenidoNombreArbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 210, 30));

        ConPrimerApellidoArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConPrimerApellidoArbitroActionPerformed(evt);
            }
        });
        getContentPane().add(ConPrimerApellidoArbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 210, 30));
        getContentPane().add(ContSegundoAPellidoArbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 210, 30));

        ContenidoTipoArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContenidoTipoArbitroActionPerformed(evt);
            }
        });
        getContentPane().add(ContenidoTipoArbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 210, 30));

        ContenidoIdentificacionArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContenidoIdentificacionArbitroActionPerformed(evt);
            }
        });
        getContentPane().add(ContenidoIdentificacionArbitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 210, 30));

        BotonIngresar.setBackground(java.awt.Color.black);
        BotonIngresar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BotonIngresar.setForeground(java.awt.Color.white);
        BotonIngresar.setText("Ingresar");
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, 130, 40));

        Atras.setBackground(new java.awt.Color(0, 0, 0));
        Atras.setFont(Atras.getFont().deriveFont(Atras.getFont().getStyle() | java.awt.Font.BOLD, Atras.getFont().getSize()+3));
        Atras.setForeground(new java.awt.Color(255, 255, 255));
        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 50, 110, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        Fondo.setText("jLabel1");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContenidoNombreArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContenidoNombreArbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContenidoNombreArbitroActionPerformed

    private void ContenidoTipoArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContenidoTipoArbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContenidoTipoArbitroActionPerformed

    private void ContenidoIdentificacionArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContenidoIdentificacionArbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContenidoIdentificacionArbitroActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.setVisible(false);
        VistaConsulta vistaCon = new VistaConsulta();
        vistaCon.setVisible(true);

    }//GEN-LAST:event_AtrasActionPerformed

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
        Arbitro  arbitro = new Arbitro();
        String nombre = ContenidoNombreArbitro.getText();
        String apellido1 = ConPrimerApellidoArbitro.getText();
        String apellido2 = ContSegundoAPellidoArbitro.getText();
        int tipodeArbitro =Integer.parseInt(ContenidoTipoArbitro.getText());
        int id = Integer.parseInt(ContenidoIdentificacionArbitro.getText());
        arbitro.AgregarArbitro(id, nombre, apellido1, apellido2, tipodeArbitro);
        ContenidoNombreArbitro.setText("");
        ConPrimerApellidoArbitro.setText("");
        ContSegundoAPellidoArbitro.setText("");
        ContenidoTipoArbitro.setText("");
        ContenidoIdentificacionArbitro.setText("");
              
    }//GEN-LAST:event_BotonIngresarActionPerformed

    private void ConPrimerApellidoArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConPrimerApellidoArbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConPrimerApellidoArbitroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void correr() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroArbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroArbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroArbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroArbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroArbitro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JTextField ConPrimerApellidoArbitro;
    private javax.swing.JTextField ContSegundoAPellidoArbitro;
    private javax.swing.JTextField ContenidoIdentificacionArbitro;
    private javax.swing.JTextField ContenidoNombreArbitro;
    private javax.swing.JTextField ContenidoTipoArbitro;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel NombreArbitro;
    private javax.swing.JLabel NombreArbitro1;
    private javax.swing.JLabel NombreArbitro2;
    private javax.swing.JLabel NombreArbitro3;
    private javax.swing.JLabel NombreArbitro4;
    private javax.swing.JLabel RegistroArbitro;
    // End of variables declaration//GEN-END:variables
}
