/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_db;

import conection.MySQL;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class VistaTablaPosiciones extends javax.swing.JFrame {

    /**
     * Creates new form VistaTablaPosiciones
     */
    public VistaTablaPosiciones() {
        initComponents();
        DefaultTableModel mod = new DefaultTableModel();
        mod.addColumn("Equipo");
        mod.addColumn("Puntos");
        TablaDePosiciones.setModel(mod);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        PedirTabla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDePosiciones = new javax.swing.JTable();
        Atras = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        Titulo.setForeground(java.awt.Color.white);
        Titulo.setText("Tabla de Posiciones ");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 490, 50));

        PedirTabla.setBackground(new java.awt.Color(0, 0, 0));
        PedirTabla.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        PedirTabla.setForeground(new java.awt.Color(255, 255, 255));
        PedirTabla.setText("Solicitar Tabla de Posiciones");
        PedirTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedirTablaActionPerformed(evt);
            }
        });
        getContentPane().add(PedirTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 320, 90));

        TablaDePosiciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaDePosiciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 530, 280));

        Atras.setBackground(new java.awt.Color(0, 0, 0));
        Atras.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Atras.setForeground(new java.awt.Color(255, 255, 255));
        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 120, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        Fondo.setText("Fondo");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1800, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void PedirTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedirTablaActionPerformed
        MySQL db = new MySQL();
        db.MySQLConnect();
        
        DefaultTableModel mod = new DefaultTableModel();
        mod.addColumn("Equipo");
        mod.addColumn("Puntos");
        TablaDePosiciones.setModel(mod);
        try{
            
        db.comando = db.conexion.createStatement();
        db.registro = db.comando.executeQuery("select nombre,puntos from Equipo group by idEquipo order by puntos desc;");
        String [] datos = new String [2];
        while(db.registro.next()){
            datos[0]=db.registro.getString(1);
            datos[1]=db.registro.getString(2);
            mod.addRow(datos);
        }

        db.close();
        }catch(Exception e){
            System.out.println(e);
        }    
    }//GEN-LAST:event_PedirTablaActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.setVisible(false);
        Main mn = new Main();
        mn.setVisible(true);
    }//GEN-LAST:event_AtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void correr() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTablaPosiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTablaPosiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTablaPosiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTablaPosiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaTablaPosiciones().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton PedirTabla;
    private javax.swing.JTable TablaDePosiciones;
    private javax.swing.JLabel Titulo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
