/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_db;
import conection.IngresarSancionados;
/**
 *
 * @author usuario
 */
public class VistaIngresarSancionados extends javax.swing.JFrame {
    int idPartido;

    /**
     * Creates new form VistaIngresarSancionados
     */
    public VistaIngresarSancionados() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        CantidadDeGoles = new javax.swing.JTextField();
        Ingresar = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        NombreJugador = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BotonIngrsar = new javax.swing.JButton();
        BotonAtras = new javax.swing.JButton();
        TipoAmonestacion = new javax.swing.JTextField();
        IdPartido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel2.setText("Nombre del Jugador");

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel3.setText("Cantidad de Goles");

        jTextField1.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jTextField1.setText("                                           ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        CantidadDeGoles.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        CantidadDeGoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadDeGolesActionPerformed(evt);
            }
        });

        Ingresar.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        Ingresar.setText("Ingresar");

        Atras.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        Atras.setText("Atrás");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreJugador.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        NombreJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(NombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 210, 30));

        Titulo.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        Titulo.setForeground(java.awt.Color.black);
        Titulo.setText("Amonestación");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 340, 40));

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de amonestación");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre del Jugador");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        BotonIngrsar.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        BotonIngrsar.setForeground(java.awt.Color.black);
        BotonIngrsar.setText("Ingresar");
        BotonIngrsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngrsarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonIngrsar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        BotonAtras.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        BotonAtras.setForeground(java.awt.Color.black);
        BotonAtras.setText("Cerrar");
        BotonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        TipoAmonestacion.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        TipoAmonestacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoAmonestacionActionPerformed(evt);
            }
        });
        getContentPane().add(TipoAmonestacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 210, 30));

        IdPartido.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        IdPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdPartidoActionPerformed(evt);
            }
        });
        getContentPane().add(IdPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 210, 30));

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Identificacion del Partido");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/amonestacion.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 480, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void CantidadDeGolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadDeGolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadDeGolesActionPerformed

    private void NombreJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreJugadorActionPerformed

    private void TipoAmonestacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoAmonestacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoAmonestacionActionPerformed

    private void BotonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasActionPerformed
      this.setVisible(false);
    }//GEN-LAST:event_BotonAtrasActionPerformed

    private void BotonIngrsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngrsarActionPerformed
        IngresarSancionados is = new IngresarSancionados();
        is.ingSancionados(NombreJugador.getText(), Integer.parseInt(TipoAmonestacion.getText()), Integer.parseInt(IdPartido.getText()));
        NombreJugador.setText("");
        TipoAmonestacion.setText("");
        IdPartido.setText("");
        
    }//GEN-LAST:event_BotonIngrsarActionPerformed

    private void IdPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdPartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdPartidoActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void correr() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaIngresarSancionados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaIngresarSancionados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaIngresarSancionados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaIngresarSancionados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaIngresarSancionados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton BotonAtras;
    private javax.swing.JButton BotonIngrsar;
    private javax.swing.JTextField CantidadDeGoles;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField IdPartido;
    private javax.swing.JButton Ingresar;
    private javax.swing.JTextField NombreJugador;
    private javax.swing.JTextField TipoAmonestacion;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
